CREATE TABLE IF NOT EXISTS ai_conversation (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  family_id BIGINT UNSIGNED NOT NULL,
  baby_id BIGINT UNSIGNED NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  client_request_id CHAR(36) NOT NULL,
  title VARCHAR(120) NOT NULL,
  status VARCHAR(24) NOT NULL COMMENT 'ANALYZING/RESPONDING/READY/FAILED',
  model VARCHAR(80) NOT NULL,
  last_error_code VARCHAR(48) NULL,
  data_processing_accepted_at DATETIME(3) NOT NULL,
  archived_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_conversation_request (family_id, baby_id, client_request_id),
  KEY idx_ai_conversation_scope (family_id, baby_id, archived_at, updated_at),
  KEY idx_ai_conversation_creator (created_by, created_at),
  CONSTRAINT fk_ai_conversation_family FOREIGN KEY (family_id) REFERENCES family(id),
  CONSTRAINT fk_ai_conversation_baby FOREIGN KEY (baby_id) REFERENCES baby(id),
  CONSTRAINT fk_ai_conversation_creator FOREIGN KEY (created_by) REFERENCES app_user(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ai_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  conversation_id BIGINT UNSIGNED NOT NULL,
  family_id BIGINT UNSIGNED NOT NULL,
  baby_id BIGINT UNSIGNED NOT NULL,
  snapshot_at DATETIME(3) NOT NULL,
  range_start DATETIME(3) NULL,
  range_end DATETIME(3) NOT NULL,
  source_event_count INT UNSIGNED NOT NULL,
  prompt_version VARCHAR(48) NOT NULL,
  dashboard JSON NOT NULL,
  prompt_text MEDIUMTEXT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_ai_snapshot_scope (family_id, baby_id, conversation_id, snapshot_at),
  KEY idx_ai_snapshot_conversation (conversation_id, id),
  CONSTRAINT fk_ai_snapshot_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversation(id),
  CONSTRAINT fk_ai_snapshot_family FOREIGN KEY (family_id) REFERENCES family(id),
  CONSTRAINT fk_ai_snapshot_baby FOREIGN KEY (baby_id) REFERENCES baby(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ai_message (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  conversation_id BIGINT UNSIGNED NOT NULL,
  family_id BIGINT UNSIGNED NOT NULL,
  baby_id BIGINT UNSIGNED NOT NULL,
  author_user_id BIGINT UNSIGNED NULL,
  client_message_id CHAR(36) NULL,
  role VARCHAR(16) NOT NULL COMMENT 'USER/ASSISTANT',
  status VARCHAR(16) NOT NULL COMMENT 'PENDING/COMPLETED/FAILED',
  content TEXT NULL,
  snapshot_id BIGINT UNSIGNED NULL,
  error_code VARCHAR(48) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_message_request (conversation_id, role, client_message_id),
  KEY idx_ai_message_scope (family_id, baby_id, conversation_id, id),
  KEY idx_ai_message_author_rate (author_user_id, created_at),
  KEY idx_ai_message_snapshot (snapshot_id),
  CONSTRAINT fk_ai_message_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversation(id),
  CONSTRAINT fk_ai_message_family FOREIGN KEY (family_id) REFERENCES family(id),
  CONSTRAINT fk_ai_message_baby FOREIGN KEY (baby_id) REFERENCES baby(id),
  CONSTRAINT fk_ai_message_author FOREIGN KEY (author_user_id) REFERENCES app_user(id),
  CONSTRAINT fk_ai_message_snapshot FOREIGN KEY (snapshot_id) REFERENCES ai_snapshot(id)
) ENGINE=InnoDB;
